In [2]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])

print(x + y , x * y , x / y , x ** y)

tensor([5.]) tensor([6.]) tensor([1.5000]) tensor([9.])


In [8]:
x = torch.arange(4)
print(x)
print(x[3])
print(len(x))
print(x.shape)

tensor([0, 1, 2, 3])
tensor(3)
4
torch.Size([4])


In [10]:
A = torch.arange(20).reshape(5,4)
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [13]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
print(B.T)
print(B == B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [14]:
X = torch.arange(24).reshape(2,3,4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [16]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
print(A)
print(A + B)
print(A * B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [17]:
a = 2
X = torch.arange(24).reshape(2,3,4)
print(a + X)
print((a + X).shape)

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


In [18]:
x = torch.arange(4,dtype = torch.float32)
print(x)
print(x.sum())

tensor([0., 1., 2., 3.])
tensor(6.)


In [31]:
A = torch.arange(40).reshape(2,5,4)
print(A)
print(A.shape)
print(A.sum())
print('---------')
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0)
print(A_sum_axis0.shape)
print('---------')
A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1)
print(A_sum_axis1.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
torch.Size([2, 5, 4])
tensor(780)
---------
tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])
torch.Size([5, 4])
---------
tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])
torch.Size([2, 4])
---------
tensor(19.5000)


In [36]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
print(A)
print(A.mean())
print(A.sum()/A.numel())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(9.5000)
tensor(9.5000)


In [35]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
print(A)
print(A.mean(axis=0))
print(A.sum(axis=0)/A.shape[0])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([ 8.,  9., 10., 11.])
tensor([ 8.,  9., 10., 11.])


In [40]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
sum_A = A.sum(axis=1,keepdims=True)
print(A)
print(sum_A)
print(A/sum_A)
print(A.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [42]:
y = torch.ones(4,dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x,y))
print(torch.sum(x*y))

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)
tensor(6.)


In [44]:
print(A.shape)
print(x.shape)
print(A,x)
print(torch.mv(A,x))

torch.Size([5, 4])
torch.Size([4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([0., 1., 2., 3.])
tensor([ 14.,  38.,  62.,  86., 110.])


In [45]:
B = torch.ones(4,3)
print(torch.mm(A,B))

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [46]:
#L2范数运算，即求此向量所有元素平方之和的算数平方根，类似勾股定理
u = torch.tensor([3.0,-4.0])
print(torch.norm(u))

tensor(5.)


In [47]:
#L1范数，即向量元素的绝对值之和
print(torch.abs(u).sum())

tensor(7.)


In [48]:
#矩阵的弗罗贝尼乌斯范数（Frobenius norm），即矩阵元素的平方和的平方根
print(torch.norm(torch.ones((4,9))))

tensor(6.)
