In [1]:
import torch

x = torch.arange(4.0,requires_grad=True)
#等价于:
# x = torch.arange(4.0)
# x.requires_grad_(True)
print(x)
print(x.grad)

tensor([0., 1., 2., 3.], requires_grad=True)
None


In [2]:
y = 2 * torch.dot(x,x)
print(y)

tensor(28., grad_fn=<MulBackward0>)


In [3]:
#调用反向传播函数来自动计算y关于x每个分量的梯度
y = 2 * torch.dot(x,x)
y.backward()
print(x.grad)
print(x.grad == 4 * x)

tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])


In [4]:
x.grad.zero_()
y = x.sum()
#y = x1+x2+x3+x4 求偏导可得[1,1,1,1]
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


In [5]:
#梯度清零
x.grad.zero_()
y = x * x
y.sum().backward()
#y = (x1)**2 + (x2)**2 + (x3)**2 + (x4)**2 求偏导即[2*x1,2*x2,2*x3,2*x4]
print(x.grad)

tensor([0., 2., 4., 6.])


In [6]:
x.grad.zero_()
y = x * x
#新的张量u与y相同但不会被视作x的函数导致参与求导，而是被视作常数，同时u也不会随x数值变化而变化
u = y.detach()
print(u)
z = u * x
z.sum().backward()
print(x.grad == u)

tensor([0., 1., 4., 9.])
tensor([True, True, True, True])


In [7]:
x.grad.zero_()
y.sum().backward()
print(x.grad == 2 * x)

tensor([True, True, True, True])
