In [1]:
import torch
num_inputs = 784
num_outputs = 10
w = torch.normal(0,0.01,size=(num_inputs,num_outputs),requires_grad=True)
b = torch.zeros(num_outputs,requires_grad=True)

x = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(x.sum(0,keepdim = True))
print(x.sum(1,keepdim = True))

tensor([[5., 7., 9.]])
tensor([[ 6.],
        [15.]])


In [2]:
def softmax(x):
    x_exp = torch.exp(x)
    partition = x_exp.sum(1,keepdim = True)
    return x_exp/partition

x = torch.normal(0,1,(2,5))
x_prob = softmax(x)
print(x_prob)
print(x_prob.sum(1))

def net(x):
    return softmax(torch.matmul(x.reshape((-1,w.shape[0])), w) + b)

tensor([[0.0792, 0.3845, 0.0750, 0.0814, 0.3799],
        [0.2213, 0.0722, 0.3449, 0.2370, 0.1247]])
tensor([1.0000, 1.0000])


In [3]:
y = torch.tensor([0,2])
y_hat = torch.tensor([[0.1,0.3,0.6],[0.3,0.2,0.5]])
print(y_hat[[0,1],y])

tensor([0.1000, 0.5000])


In [4]:
def cross_entropy(y_hat,y):
    return -torch.log(y_hat[range(len(y_hat)),y])

print(cross_entropy(y_hat,y))

tensor([2.3026, 0.6931])


In [5]:
def accuracy(y_hat,y):
    '''计算预测正确的数量'''
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis = 1)
    cmp = y_hat.type(y.dtype) == y
    return float(cmp.type(y.dtype).sum())

print(accuracy(y_hat,y)/len(y))

In [6]:
def evaluate_accuracy(net,data_iter):
    '''计算在指定数据集上模型的精度'''
    if isinstance(net,torch.nn.Module):
        net.eval()
    metric = Accumulator(2)
    for x,y in data_iter:
        metric.add(accuracy(net(x),y),y.numel())
    return metric[0]/metric[1]

class Accumulator:
    def __init__(self,n):
        self.data = [0.0] * n

    def add(self,*args):
        self.data = [a + float(b) for a,b in zip(self.data,args)]

    def reset(self):
        self.data = [0.0] * len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]