In [2]:
import torch
from torch import nn

from 感知机 import num_hiddens


#以dropout的概率丢弃张量x中的元素
def dropout_layer(x,dropout):
    #限制dropout的范围，在0到1道
    assert 0 <= dropout <= 1
    #当dropout为1时，抛弃所有元素，只剩0，返回与张量x相同大小的零张量
    if dropout == 1:
        return torch.zeros_like(x)
    #当dropout为0时，不抛弃任何元素，直接返回原张量x
    if dropout == 0:
        return x

    mask = (torch.randn(x.shape) > dropout).float()
    return mask * x / (1.0 - dropout)

In [4]:
X = torch.arange(16,dtype = torch.float32).reshape(2,8)

print(X)
print(dropout_layer(X,0))
print(dropout_layer(X,0.5))
print(dropout_layer(X,1))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.],
        [16.,  0., 20.,  0.,  0.,  0.,  0., 30.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
#定义具有两个隐藏层的多层感知机，每个隐藏层包含256个单元
num_inputs,num_outputs,num_hiddens1,num_hiddens2 = 784,10,256,256
dropout1 = 0.2
dropout2 = 0.5

class Net(nn.Module):
    def __init__(self,num_inputs,num_outputs,num_hiddens1,num_hiddens2,is_training=True):
        super(Net,self).__init__()
        self.is_training = is_training
        self.num_inputs = num_inputs
        self.lin1 = nn.Linear(num_inputs,num_hiddens1)
        self.lin2 = nn.Linear(num_hiddens1,num_hiddens2)
        self.lin3 = nn.Linear(num_hiddens2,num_outputs)
        self.relu = nn.ReLU()

    def forward(self,x):
        H1 = self.relu(self.lin1(x.reshape(-1,self.num_input)))
        if self.training == True:
            H1 = dropout_layer(H1,dropout1)
        H2 = self.relu(self.lin2(H1))
        if self.training == True:
            H2 = dropout_layer(H2,dropout2)
        out = self.lin3(H2)
        return out

net = Net(num_inputs,num_outputs,num_hiddens1,num_hiddens2,is_training=True)